name: ipeo_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - cpuonly=2.0=0
  - filelock=3.19.1=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=78.2=h637d24d_0
  - idna=3.11=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.54=h7351971_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=h29ce207_0
  - markupsafe=3.0.2=py39hf73967f_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=h0e40799_1002
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.23=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.23=h8c5b53a_0_cpython
  - python_abi=3.9=8_cp39
  - pytorch=2.5.1=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.2=py39h827c3e9_0
  - requests=2.32.5=py39haa95532_0
  - scikit-learn=1.6.1=py39hdd013cc_0
  - scipy=1.13.1=py39h8640f81_1
  - setuptools=80.9.0=pyhff2d567_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=h3155e25_5
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_3
  - torchaudio=2.5.1=py39_cpu
  - torchvision=0.15.2=cpu_py39h7187fe4_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=py39haa95532_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=py39haa95532_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - yaml=0.2.5=he774522_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - asttokens==3.0.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fonttools==4.60.2
      - fsspec==2025.10.0
      - huggingface-hub==0.36.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - ipykernel==6.31.0
      - ipython==8.18.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - packaging==25.0
      - parso==0.8.5
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pywin32==311
      - pyzmq==27.1.0
      - regex==2026.1.15
      - safetensors==0.7.0
      - six==1.17.0
      - stack-data==0.6.3
      - tokenizers==0.22.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.5
      - wcwidth==0.2.14
      - zipp==3.23.0
prefix: C:\Users\prana\miniconda3\envs\ipeo_env
