name: ipeo_env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - scikit-learn
  - pillow
  - pip

  - pip:
      - transformers
      - tokenizers
      - tqdm
      - regex
      - matplotlib
      - ipykernel
      - gdown
      - timm

