name: ipeo_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpuonly=2.0
  - filelock=3.19.1
  - icc_rt=2022.1.0
  - icu=78.2
  - idna=3.11
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - lcms2=2.18
  - lerc=4.0.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblzma=5.8.1
  - libpng=1.6.54
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pybind11-abi=5
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.9.23
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.5
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=80.9.0
  - sympy=1.14.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchvision=0.15.2
  - typing_extensions=4.14.1
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zstd=1.5.7
  - pip:
      - asttokens==3.0.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fonttools==4.60.2
      - fsspec==2025.10.0
      - huggingface-hub==0.36.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - ipykernel==6.31.0
      - ipython==8.18.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - packaging==25.0
      - parso==0.8.5
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pywin32==311
      - pyzmq==27.1.0
      - regex==2026.1.15
      - safetensors==0.7.0
      - six==1.17.0
      - stack-data==0.6.3
      - tokenizers==0.22.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.5
      - wcwidth==0.2.14
      - zipp==3.23.0
prefix: C:\Users\prana\miniconda3\envs\ipeo_env
